# pyproject.toml

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysnowclim"
version = "0.1.0"
description = "A standalone package for the pySnowclim hydrological module."
authors = [{ name = "Abby"}, { name = "Aranildo"}, { name = "Raj"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.19.0",
    "xarray>=0.18.0",
    "scipy>=1.6.0",
    "netCDF4>=1.5.0",
    "pandas>=1.2.0",
    "requests>=2.25.0",
    "matplotlib>=3.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=21.0",
    "mypy>=0.900",
    "pytest-cov>=2.12.0",
]

[tool.pytest.ini_options]
# Specifies the directory where tests are located
pythonpath = "src"
testpaths = "tests"

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']

[project.urls]
Homepage = "https://github.com/abbylute/pySnowClim"
Repository = "https://github.com/abbylute/pySnowClim"
Issues = "https://github.com/abbylute/pySnowClim/issues"
